#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
# (hd0) disk.img

geometry (hd0) 88 16 63
root (hd0,1)
setup (hd0)
kernel /boot/grub/kernel.bin
